### ISSUE TITLE
I Place Crystal Growth Chamber and Game crash

### ISSUE THREAD

**Issue by Tsyklop** [bdew/ae2stuff#12]
Log: http://pastebin.com/DBkXFnyh

AE2 rv2 beta8

**Comment by bdew** [comment]
Your crash doesn't even mention my mod. Are you sure that you weren't using something from [AE2 Tech](http://minecraft.curseforge.com/mc-mods/221903-ae2-tech-add-on)?

**Comment by Tsyklop** [comment]
using. But I place block in Ae2Stuff and game crash

**Comment by bdew** [comment]
Well this log doesn't give me anything useful to see what the problem is. Can you try if it still crashes without any AE2 Tech blocks on the same network?

**Comment by bdew** [comment]
I've opened a bug report on AE2 Tech tracker as well: https://bitbucket.org/FireBall1725/ae2techaddon/issue/9/crash-when-used-with-ae2-stuff

**Comment by FireBall1725** [comment]
@Tsyklop how is the network setup, can you provide a screen shot, and some more info so i can try to reproduce?

**Comment by Tsyklop** [comment]
@FireBall1725 I install onle AE2 rv2 beta8 and ae2stuff and all OK. Sorry.

**Comment by Avodroc** [comment]
Old post, but I know the issue after some trial and error. The Crystal Growth Chamber causes a crash in 1.7.10 because once you place it, it is receiving power without a power source actually connected to it. The game crashes and if you load it back up, the problem is gone. Every time you place a Crystal Growth Chamber, the crash will happen unless fixed by the creator. After the crash, you can sucessfully load up the world and continue.

**Comment by bdew** [comment]
If you are using the right version combination - nothing should be crashing.

If it does - post the logs.
