### ISSUE TITLE
Wireless connectors do not work in other dimensions.

### ISSUE THREAD

**Issue by jpeaglesandkatz** [bdew/ae2stuff#121]
Using AE2-beta 6 for 1.10.2 and latest AE2Stuff
ae2stuff-0.6.0.6-mc1.10.2

Trying to setup some wireless connectors in my void base (rftools dimension) world.

Gives me this red message in the chat. "Both connectors must be in the same dimension"

Is this not implemented, wireless connectors working in other dimensions but the overworld. Would be great if they did.

Update:>> ok. they do work. But you need to craft a new network setup kit because somehow the one I was using the overworld keeps being bound to some receiver and there is no way to clear the setup kit (shift-right clicking with the setup kit in hand) to clear it would be nice.

**Comment by bdew** [comment]
Should be fixed in nest build.

Right clicking on a wireless connector in another dimension should have "reset" the remembered position in the item - this wasn't working due to a bug, which is now fixed.

Also you can now force reset it by shift-rightclick with the item in hand (though that shouldn't really be required).
