### ISSUE TITLE
Automating the Advanced Inscriber

### ISSUE THREAD

**Issue by Coolfeather2** [bdew/ae2stuff#150]
![2017-08-12_12 23 21](https://user-images.githubusercontent.com/14107982/29237816-24ff5a92-7f59-11e7-92a1-1954c315e84a.png)
![2017-08-12_12 23 27](https://user-images.githubusercontent.com/14107982/29237817-269198ca-7f59-11e7-995e-8d25aa7363f1.png)
Tried automating it but having the circuit + press both in the output causes the pattern to be the crafting result

**Comment by Bass2style** [comment]
i had the same issue.

i made 5 inscribers, locked 4 ones with a press in it, and removed the press from the recipes (from the patterns), and withelisted the things that need to be pushed to the inscribers.

**Comment by Coolfeather2** [comment]
Then what's the point of using advanced inscribers?

**Comment by Bass2style** [comment]
his speed and his capability of stacking are the most obvious reasons, and it's simplyier to automate it than the normal inscribers.

edit : second précision about automation : 

i had to to this beceause the autocrafting system from AE2 is a bit tricky.
when using the inscriber press directly in the pattern, AE2 asked one press per craft.
exemple : i need 10 logic processor, the system ask for 10 silicon press, and 10 logic press.
i had to remove the presses from the crafting pattern, and lock it into the inscriber.


edit 2 : outch, not understand correctly your problem, i had understand that the press comes back in the system directly without crafting or something like that.

viewing the screens with more attention triggered my error.

realy strange issue, not noticed that before, but is seems to be string inversions in the pattern, could that be an AE2 error ? because i never had this, but i'm not on the final (RV4 stable 1) version of AE2 for 1.10 actually, but always on the RV4_Alpha11, and i don't have such issues.

**Comment by Coolfeather2** [comment]
I think it has something to do with the id + nbt tag, the press has a higher nbt tag than the circuit
