### ISSUE TITLE
[1.12.2] Server crashing with ae2stuff 0.7.0.1 and AE2 RV5 alpha 8

### ISSUE THREAD

**Issue by digi-tal-it** [bdew/ae2stuff#154]
My 1.12.2 server keeps crashing after updating AE2 vom alpha 7 to alpha 8:

Here is the crashlog:

https://pastebin.com/bWL5HJXK

**Comment by yueh** [comment]
As a quick note, we moved the factory methods for grid related objects into their own helper (`AEApi.instance().grid()`).

This is mainly intended to improve our injection annotation in the future. In particular to avoid reflecting from the API into the core or being able to inject just the required helper into another mod.
As we probably are not able to provide a real DI, it will most likely be limited to injecting them into static fields/methods or similar to JEI by instantiating the class and then passing the helper into it and leave it to the mod to handle anything afterwards.
The static access will of course still stay, it will just be an alternative for some cases.

Also due to the changes to `StorageChannel`, you will have to update the pattern encoder to use the API method `AEApi.instance().storage().getStorageChannel( IItemStorageChannel.class ).createStack( itemStack )` not the internal one. (Avoiding these long chains is another reason..)

**Comment by bdew** [comment]
Thanks for the report, i'll try to make an update tomorrow.

**Comment by bdew** [comment]
Version 0.7.0.2 will be out in a sec with support for alpha 8.

**Comment by yueh** [comment]
Just for the future. If you want, I could create a PR for smaller API changes. 

Also `IAEItemStack.createItemStack()` already creates a clean copy, so no need to copy it again.

**Comment by bdew** [comment]
I won't say no to any offers of help, but don't worry about it too much.

I'll remove the unnecessary copy.
