### ISSUE TITLE
Crystal Growth Chamber Sleeping Since May 10th Update.

### ISSUE THREAD

**Issue by KaneHart** [bdew/ae2stuff#21]
Not sure what happen but no matter if I connect via cable or anything it is always sleeping.

http://i.imgur.com/3FRwL0m.png

http://i.imgur.com/2cDwF0P.png

**Comment by bdew** [comment]
I've changed how it interacts with AE2 network power storage. 

The old version was using passive power drain which would often cause blackouts of the whole network if power supply wasn't adequate that would either cycle on-off (causing server lag) or just stay permanently off without making any progress. This is even worse with added speed upgrades.

The new system uses an active power draw with some logic added to prevent blackouts (it will only draw when total power storage in the network is above 20% capacity, and will never draw more than 10% of the total capacity). It also allows it to throttle itself down to operate slowly in case of inadequate power instead of killing everything.

However the new system requires actually having power storage on the network, which means either a controller or energy cell has to be present on the network. Otherwise it won't draw power (that's why you see 0 AE stored) and sleep forever.

This system is something i'd like to improve in the future and i'm open to suggestions.

**Comment by bdew** [comment]
This should make your setup work and be more sensible in general, allowing both output from energy sources (like the acceptor) and energy storage (cells/controllers)
