### ISSUE TITLE
[Bug] Incorrect number of ingridients on encoded pattern.

### ISSUE THREAD

**Issue by FREEZEball** [bdew/ae2stuff#47]
Trying to encode pattern with recipes of Applied Energistics 2's [ME Dense Cable](http://ae-mod.info/ME-Dense-Cable/) or [ME Smart Cable](http://ae-mod.info/ME-Smart-Cable/) results in incorrect number of needed ingridients:

![pic1](http://i.imgur.com/pv0L5Od.png)
![pic2](http://i.imgur.com/YNvNJtS.png)

Both recipes taken from NEI (shift-clicking the '?' button). Child recipes (colored cables) work correctly. Encoding same recipes with AE2 Pattern Terminal works correctly. When I try to auto-craft with these (or child) recipes, auto-crafting stuck on simulation mode.

Minecraft 1.7.10
Forge 10.13.4.1490
Applied Energistics rv2 stable 10
AE2Stuff 0.4.3.45

**Comment by bdew** [comment]
Hmm guess i broke something with the fix to #46

**Comment by FREEZEball** [comment]
No, no, it happened at 0.4.0.38 too, I just forgot to add it yesterday.

**Comment by bdew** [comment]
The issue was that some recipes had 0 sized stacks in NEI, which my code transfered into the pattern.

With this fix it will always force stack size to 1 for normal crafting.

Should be fixed in this build - http://jenkins.bdew.net/job/ae2stuff-1.7.10/46/artifact/build/libs/ae2stuff-0.4.3.46-mc1.7.10.jar
