### ISSUE TITLE
Suggestion/Request: Ship configs or an example config template

### ISSUE THREAD

**Issue by PsionicArchon** [bdew/ae2stuff#90]
I've been searching for a means of reducing the power usage of wireless connectors for the past hour now.

I'd like to bring them in line with the quantum bridge. I feel that, at max range, a wireless connection should NEVER exceed the power usage of a quantum bridge.

With the current implementation of wireless connections, at 64(ish) blocks a wireless bridge will use around 2182 rf/t on BOTH ENDS. That's a whopping 4365 rf/t. A quantum link uses 800rf/t to accomplish the same task and works across dimensions. 

For a poorman's quantum link, these things sure suck down power. 

Is there a way to reduce this blocks power usage that I'm just missing? Config folders are empty. Searching Google has yielded nothing. Also, as a side note, would you consider reducing the power usage of these devices by default? 

I was counting on these things providing a cheaper quantum bridge alternative for users on my server. Once people plunk these suckers down I foresee them switching away to quantum bridges rather quickly.

Thanks in advance.

**Comment by bdew** [comment]
They are designed to scale up in power usage to become impractical over longer distances, if they always used less than a quantum bridge - no one would ever use a quantum bridge, because they really have no other drawback except power use. This is not my goal.

You can look at the default configs [here](https://github.com/bdew/ae2stuff/tree/master/resources/assets/ae2stuff/config) to use them as an example and the format is documented [here](http://bdew.net/bacon/). There will be more and better documentation on configuration once the mod is more mature.

To change the power used by wireless connectors, make a file in ae2stuff config directory, named **\<whatever>.cfg** with the folowing content:

```
cfg Machines {
    cfg Wireless {
        // Power use = PowerBase + PowerDistanceMultiplier * Distance^2 (AE/t)
        PowerBase = 10
        PowerDistanceMultiplier = 1
    }
}
```

**Comment by ghost** [comment]
Thank you very much :+1:
